### ISSUE TITLE
Use

### ISSUE THREAD

**Issue by Janasek** [pyload/pyload-plugins#7]
Hi

how to use ?

**Comment by GammaC0de** [comment]
Use what?

**Comment by Janasek** [comment]
pyload-plugins

**Comment by GammaC0de** [comment]
Have you installed pyload?

**Comment by Janasek** [comment]
No

**Comment by GammaC0de** [comment]
On what Hardware / Operating System do you want to install pyload?

**Comment by Janasek** [comment]
sorry my friend
I would like to install it on kodi 17.6 and 18
Windows-Android-LibreElec
